### ISSUE TITLE
Reporting Enhancements

### ISSUE THREAD

**Issue by tjdavis3** [teliax/ivy-issues#9]
Current reports merely create a CSV that is available for download and only to administration.  This project will allow users to pull up their generated reports and view them.  It will also be available to partnerships.

Advanced functionality _may_ provide the user the ability to design reports.

**Comment by gaurav-teliax** [comment]
@tjdavis3: Had a quick question. The ticket says we will be showing the reports for a partner. Do we need to any reports for partners? or these reports are going to be the ones run in the admin section?

**Comment by tjdavis3** [comment]
They will be some of the ones in admin, but limited to that partner.  We need to evaluate which ones to provide to them (911 is probably a good one, and maybe manual transactions).  We'll want to evaluate the others.
